---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 12165.
--- DateTime: 2024/3/18 14:38

-- 设置用户访问频率限制的参数
local username = KEYS[1]
local url = KEYS[2]
local timeWindow = tonumber(ARGV[1]) -- 时间窗口，单位：秒

-- 构造 Redis 中存储用户访问次数的键名
local accessKey = "user-flow-risk-control:" .. username .. ":" ..url

-- 原子递增访问次数，并获取递增后的值
local currentAccessCount = redis.call("INCR", accessKey)

-- 设置键的过期时间
redis.call("EXPIRE", accessKey, timeWindow)

-- 返回当前访问次数
return currentAccessCount