server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.78.129
      port: 5000
  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  stats:
    locale:
      amap-key: 5c31440fac9c414375f6d97b3785bf98

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: 192.168.78.129:9876
  producer:
    group: short-link-producer-group